### ISSUE TITLE
Find a way to capture frame from limelight's mjpg stream.

### ISSUE THREAD

**Issue by tm1287** [Team1100/FRCPowerUp#16]
Stream is located at http://10.11.00.11:5800. We want to be able to capture ONE frame only if limelight.getInstance().getArea() != -1. We want to be able to take pictures during the match in order to correctly assign HSV values.

**Comment by GrantPerkins** [comment]
After spending 5 hours today on it im stumped

**Comment by thomashayden** [comment]
By capture, do you mean save the image for later analysis?

**Comment by GrantPerkins** [comment]
Yes, we want to configure our hsv values based on real-match images

**Comment by thomashayden** [comment]
So, as far as I can tell there is no built in way for the limelight to save images. This makes everything a lot more annoying. Now I can't test any of this because I obviously don't have a limelight, RIO, or a DS, but here is what I would try. Figure out how to access the camera stream directly from your Java code. Then figure out how to save an image from there (this is likely as simple as using the standard Java file library). Optionally, you could try to figure out how to send the image/image file to the DS (I don't know how hard this would be with the network constraints). If you don't send the file to the DS, it will be saved somewhere on the RIO itself (hopefully you will save it somewhere logical). After the match, you can FTP into it and pull the images off. This is not really streamlined, but it's the best I could come up with assuming there is no built in way to save the image.

**Comment by GrantPerkins** [comment]
The part we need help with is accessing the mjpg stream through the code. Weve saved an opencv mat as a .jpg to the rio, then ftp'd to open it, but we couldnt access the stream

**Comment by thomashayden** [comment]
[Here](http://answers.opencv.org/question/24243/read-h264-frame-from-ip-camera-feed-java-version/) is something that seems to only use built in java libraries and looks to do what you want.

**Comment by GrantPerkins** [comment]
Thats really similar to the method attempted in CaptureImage.java, ill keep on trying that

**Comment by thomashayden** [comment]
Good luck. I think to provide more useful information I'd have to actually be there.

**Comment by GrantPerkins** [comment]
Thanks for taking time out of your day to find that. It was pretty useful!

**Comment by GrantPerkins** [comment]
Possible [external library solution](https://github.com/sarxos/webcam-capture).
 - Sorry Grant, forgot to log you off on the FRC computer

**Comment by thomashayden** [comment]
That looks promising!

**Comment by GrantPerkins** [comment]
https://github.com/LimelightVision/LimelightDocs/issues/2

**Comment by GrantPerkins** [comment]
They're making this a new feature

**Comment by thomashayden** [comment]
Fantastic! I have had success in the past by talking directly to devs of grip, so with some luck the limelight folks will implement the feature before comp season.

**Comment by tm1287** [comment]
@GrantPerkins that's awesome!!!

**Comment by GrantPerkins** [comment]
This cannot be done.

**Comment by Sn3akyP3t3** [comment]
So there is no way to acquire unaltered frames from the Limelight as an mjpeg stream or any other means?

I realize this is closed, but this was the only place a conversation like this was taking place.  I was also surprised to see anticipation with sudden issue termination with little to no explanation as to why it cannot be done.

**Comment by thomashayden** [comment]
I'm not sure why it was declared "cannot be done", but the following day @GrantPerkins posted in a Limelight issue that he figured out how to save the images. I'm not sure if the Limeline built in feature was ever added. I've never looked at the code before so I can't really explain it, but [this](https://github.com/Team1100/FRCPowerUp/blob/devcjp/src/org/usfirst/frc/team1100/robot/commands/vision/SaveCubePNG.java) is the code Grant meant to link to which supposedly saves an image.

**Comment by Sn3akyP3t3** [comment]
Thanks, I think I had better open another issue as a request then.  The code linked seems to be using port 5800 which is the documented mjpeg stream that limelight modifies with drawn-in annotations.
