### ISSUE TITLE
RIP Limelight 2017-2018

### ISSUE THREAD

**Issue by GrantPerkins** [Team1100/FRCPowerUp#23]
It didn't survive 20+ brownouts that were the result of a greedy chassis.

**Comment by thomashayden** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by tm1287** [comment]
$400 down the drain?

**Comment by GrantPerkins** [comment]
(X) to pay respects

**Comment by tm1287** [comment]
I think you mean (F)

**Comment by tm1287** [comment]
PC over console

**Comment by thomashayden** [comment]
F

**Comment by tm1287** [comment]
**Limelight Vision**, 1 month, of Northborough, Massachusetts, United States, passed Wednesday, February 14, 2018. Limelight was born January 11, 2018. Limelight provided the Algonquin FRC team with so many services, services that made vision exponentially easier. All members of Team 1100 will remember Limelight forever and keep him in our hearts forever. May he Rest in Peace.

**Comment by Joshua-Gordon** [comment]
F


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Thomas Hayden <notifications@github.com> Date: 2/15/18  9:14 PM  (GMT-05:00) To: Team1100/FRCPowerUp <FRCPowerUp@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [Team1100/FRCPowerUp] RIP Limelight 2017-2018 (#23) 
F

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Team1100/FRCPowerUp","title":"Team1100/FRCPowerUp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Team1100/FRCPowerUp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@thomashayden in #23: F"}],"action":{"name":"View Issue","url":"https://github.com/Team1100/FRCPowerUp/issues/23#issuecomment-366125990"}}}

**Comment by ghost** [comment]
Limelight is working again. Thank you to Tom Daly and Ben Lincoln at Bose.

**Comment by ghost** [comment]
Closed

**Comment by ghost** [comment]
More details:
I took the camera first to our electrical tech (Ben Lincoln) then one of our most experienced EEs (Tom Daly). The tiny inductor that burned out was likely intended to condition the voltage junk coming from the motors. When the camera lights are on, it draws close to an amp and it is unlikely the inductor could handle that for very long. The camera can work fine with the inductor terminals shorted (which we did). Additionally Tom recommended putting an inductor on the +12V supply to filter to motor noise. He gave me two.

**Comment by thomashayden** [comment]
That's fantastic news! Thanks to Tom Daly and Ben Lincoln!
